sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t hubertdf/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hubertdf/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-west-2'
  edge: 'true'
  app: 'docker'
  env: 'docker-env'
  bucket_name: 'elasticbeanstalk-us-west-2-362270374225'
  bucket_path: 'docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
